#!/usr/bin/env python3
from pathlib import Path
import sys

paths = {
    "bashrc": ".bashrc",
    "bash_profile": ".bash_profile",
    "bin/ask-llm": "bin/ask-llm",
    "bin/copy": "bin/copy",
    "bin/e": "bin/e",
    "bin/jfd": "bin/jfd",
    "bin/jjlogwatch": "bin/jjlogwatch",
    "claude/CLAUDE.md": ".claude/CLAUDE.md",
    "claude/handle-pr-feedback.md": ".claude/skills/handle-pr-feedback/SKILL.md",
    "claude/jj_workflow.md": ".claude/jj_workflow.md",
    "gitconfig": ".gitconfig",
    "graphite_nuxes": ".local/share/graphite/nuxes",
    "helix/config.toml": ".config/helix/config.toml",
    "helix/kalgykai-dark.toml": ".config/helix/themes/kalgykai-dark.toml",
    "helix/languages.toml": ".config/helix/languages.toml",
    "jj-config.toml": ".config/jj/config.toml",
    "inputrc": ".inputrc",
    "tmux.conf": ".tmux.conf",
}


def log(s: str) -> None:
    print(s, file=sys.stderr)


def install() -> None:
    for source_relpath, dest_relpath in paths.items():
        source = Path.cwd() / source_relpath
        dest = Path.home() / dest_relpath

        if not source.exists():
            log(f"MISSING {source_relpath}")
            continue

        if dest.exists() and source.samefile(dest):
            log(f"OK {dest}")
            continue

        if dest.is_file() or dest.is_symlink():
            backup = dest.with_name(f"{dest.name}-pylon")
            log(f"mv {dest} -> {backup}")
            dest.rename(backup)
        elif dest.exists():
            log(f"???? {dest}")
            continue

        if "/" in dest_relpath and not dest.parent.is_dir():
            log(f"mkdir {dest.parent}")
            dest.parent.mkdir(parents=True)

        log(f"link {dest} -> {source}")
        dest.symlink_to(source)


if __name__ == "__main__":
    install()
